# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "Brian's Blog"
tagline:             "A place for me to write things down."
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://brianpasquini.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Brian Pasquini
  url:               https://twitter.com/bpasquini
  email:             brian.pasquini@gmail.com
  github:            bpasquini
  twitter:           bpasquini

# Custom vars
version:             1.0.0
